// 内置教学案例：每个案例含正则、测试串、分步讲解与匹配看点。
export const EXAMPLES = [
  {
    id: 'email',
    name: '邮箱',
    pattern: '[\\w.]+@[\\w]+\\.[a-z]{2,}',
    sample: 'ada@example.com',
    intro: '一个教学用的简化邮箱正则：用户名部分允许字母数字下划线和点，@ 后是域名，最后是至少两位的顶级域名。',
    parts: [
      { expr: '[\\w.]+', meaning: '用户名：一个或多个字母/数字/下划线/点（贪婪）' },
      { expr: '@', meaning: '字面的 @ 分隔符' },
      { expr: '[\\w]+', meaning: '域名主体' },
      { expr: '\\.', meaning: '字面的点（. 在正则里是通配符，必须用 \\ 转义）' },
      { expr: '[a-z]{2,}', meaning: '顶级域名：至少两个小写字母' },
    ],
    watch: '留意 [\\w.]+ 的贪婪特性：它会先一路吃到底，再为匹配 @ 而回退——这是最常见的回溯场景。',
  },
  {
    id: 'url',
    name: 'URL',
    pattern: 'https?://[\\w.]+(?:/[\\w./?=&-]*)?',
    sample: 'https://example.com/path?x=1',
    intro: '匹配一个简化的 http/https 网址：协议可选 s，然后是域名，再跟一个可选的路径部分。',
    parts: [
      { expr: 'https?', meaning: 'http 加上可选的 s，同时覆盖 http 与 https' },
      { expr: '://', meaning: '字面的 :// 分隔符' },
      { expr: '[\\w.]+', meaning: '域名（含点）' },
      { expr: '(?:/[\\w./?=&-]*)?', meaning: '非捕获组：可选的路径，以 / 开头' },
    ],
    watch: '? 同时出现在两个地方：一个是字符可选（s?），一个是整组可选（…)?）。',
  },
  {
    id: 'date',
    name: '日期',
    pattern: '(\\d{4})-(\\d{2})-(\\d{2})',
    sample: '2026-09-20',
    intro: 'YYYY-MM-DD 格式的日期，包含三个捕获组，分别捕获年、月、日。',
    parts: [
      { expr: '(\\d{4})', meaning: '捕获组 1：恰好 4 位数字（年）' },
      { expr: '-', meaning: '字面连字符' },
      { expr: '(\\d{2})', meaning: '捕获组 2：恰好 2 位数字（月）' },
      { expr: '-', meaning: '字面连字符' },
      { expr: '(\\d{2})', meaning: '捕获组 3：恰好 2 位数字（日）' },
    ],
    watch: '{n} 量词不产生 split/回溯结构，它在 Thompson 构造里就是 n 份串联拷贝。',
  },
  {
    id: 'html',
    name: 'HTML 标签',
    pattern: '</?[a-z][\\w]*(?:\\s[\\w]+="[^"]*")*\\s*/?>',
    sample: '<img src="x.png" />',
    intro: '匹配一个简化的 HTML/XML 标签：可选的闭合斜杠、标签名、若干属性，最后可选自闭合斜杠。',
    parts: [
      { expr: '</?', meaning: '字面 < 加可选 /（兼容开闭标签）' },
      { expr: '[a-z][\\w]*', meaning: '标签名以字母开头，后接任意个单词字符' },
      { expr: '(?:\\s[\\w]+="[^"]*")*', meaning: '零或多个 属性名="值"；[^"]* 匹配除引号外任意内容' },
      { expr: '\\s*/?\\s*>', meaning: '可选空白与自闭合 /，最后是 >' },
    ],
    watch: '[^"]* 是取反字符类的典型用法，比 .*? 更高效且没有歧义。',
  },
  {
    id: 'catastrophic',
    name: '灾难性回溯',
    pattern: '(a+)+b',
    sample: 'aaaaaaaaaaaaaaaaaa!',
    intro: '经典的指数级回溯反例：(a+)+ 的内外层都能吃 a，当结尾 b 匹配失败时，引擎要尝试所有把 a 切分给内外层的方式（2^(n-1) 种）。',
    parts: [
      { expr: '(a+)+', meaning: '危险结构：无界重复嵌套在另一个无界重复里' },
      { expr: 'b', meaning: '结尾必须是 b；输入给了 ! 时必然失败，触发全盘回溯' },
    ],
    watch: '先用 DFA 模式播放：线性步数立刻拒绝。再切到回溯模式看帧数爆炸和性能面板的红色告警；改写为 a+b 即可消除危险。',
  },
  {
    id: 'greedy-lazy',
    name: '贪婪 vs 懒惰',
    pattern: '".*?"',
    sample: '"first" and "second"',
    intro: '对比贪婪 .* 与懒惰 .*? 的经典案例：懒惰量词在每一步都优先“退出”，因此停在第一个引号处。',
    parts: [
      { expr: '"', meaning: '开头引号' },
      { expr: '.*?', meaning: '懒惰的任意字符：能不匹配就不匹配，配合后面的 " 停在最近的引号' },
      { expr: '"', meaning: '结尾引号' },
    ],
    watch: '在匹配演示里切换贪婪/懒惰并排对比：贪婪会一口气吃到最后一个引号再往回退，懒惰则在第一个引号处成功。',
  },
];
